//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsConsoleClient.CustomerServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="customergetallresult", Namespace="http://services.it.tcg/epicor/customerservice")]
    [System.SerializableAttribute()]
    public partial class customergetallresult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string exceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsConsoleClient.CustomerServiceReference.customer[] epicorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string exception {
            get {
                return this.exceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.exceptionField, value) != true)) {
                    this.exceptionField = value;
                    this.RaisePropertyChanged("exception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public WindowsConsoleClient.CustomerServiceReference.customer[] epicor {
            get {
                return this.epicorField;
            }
            set {
                if ((object.ReferenceEquals(this.epicorField, value) != true)) {
                    this.epicorField = value;
                    this.RaisePropertyChanged("epicor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="customer", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary.GetAllCustomers")]
    [System.SerializableAttribute()]
    public partial class customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string custidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string custnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phonenumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string custid {
            get {
                return this.custidField;
            }
            set {
                if ((object.ReferenceEquals(this.custidField, value) != true)) {
                    this.custidField = value;
                    this.RaisePropertyChanged("custid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string custnum {
            get {
                return this.custnumField;
            }
            set {
                if ((object.ReferenceEquals(this.custnumField, value) != true)) {
                    this.custnumField = value;
                    this.RaisePropertyChanged("custnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phonenum {
            get {
                return this.phonenumField;
            }
            set {
                if ((object.ReferenceEquals(this.phonenumField, value) != true)) {
                    this.phonenumField = value;
                    this.RaisePropertyChanged("phonenum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state {
            get {
                return this.stateField;
            }
            set {
                if ((object.ReferenceEquals(this.stateField, value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string zip {
            get {
                return this.zipField;
            }
            set {
                if ((object.ReferenceEquals(this.zipField, value) != true)) {
                    this.zipField = value;
                    this.RaisePropertyChanged("zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="customergetsingleresult", Namespace="http://services.it.tcg/epicor/customerservice")]
    [System.SerializableAttribute()]
    public partial class customergetsingleresult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string exceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsConsoleClient.CustomerServiceReference.customer1[] epicorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string exception {
            get {
                return this.exceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.exceptionField, value) != true)) {
                    this.exceptionField = value;
                    this.RaisePropertyChanged("exception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public WindowsConsoleClient.CustomerServiceReference.customer1[] epicor {
            get {
                return this.epicorField;
            }
            set {
                if ((object.ReferenceEquals(this.epicorField, value) != true)) {
                    this.epicorField = value;
                    this.RaisePropertyChanged("epicor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="customer", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class customer1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string address3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string custidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string custnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string discountpercentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailaddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string faxnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phonenumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string specialinstructionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string staddress1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string staddress2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string staddress3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stcityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stcountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ststateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stzipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address1 {
            get {
                return this.address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.address1Field, value) != true)) {
                    this.address1Field = value;
                    this.RaisePropertyChanged("address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address2 {
            get {
                return this.address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.address2Field, value) != true)) {
                    this.address2Field = value;
                    this.RaisePropertyChanged("address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address3 {
            get {
                return this.address3Field;
            }
            set {
                if ((object.ReferenceEquals(this.address3Field, value) != true)) {
                    this.address3Field = value;
                    this.RaisePropertyChanged("address3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string country {
            get {
                return this.countryField;
            }
            set {
                if ((object.ReferenceEquals(this.countryField, value) != true)) {
                    this.countryField = value;
                    this.RaisePropertyChanged("country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string custid {
            get {
                return this.custidField;
            }
            set {
                if ((object.ReferenceEquals(this.custidField, value) != true)) {
                    this.custidField = value;
                    this.RaisePropertyChanged("custid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string custnum {
            get {
                return this.custnumField;
            }
            set {
                if ((object.ReferenceEquals(this.custnumField, value) != true)) {
                    this.custnumField = value;
                    this.RaisePropertyChanged("custnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string discountpercent {
            get {
                return this.discountpercentField;
            }
            set {
                if ((object.ReferenceEquals(this.discountpercentField, value) != true)) {
                    this.discountpercentField = value;
                    this.RaisePropertyChanged("discountpercent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emailaddress {
            get {
                return this.emailaddressField;
            }
            set {
                if ((object.ReferenceEquals(this.emailaddressField, value) != true)) {
                    this.emailaddressField = value;
                    this.RaisePropertyChanged("emailaddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string faxnum {
            get {
                return this.faxnumField;
            }
            set {
                if ((object.ReferenceEquals(this.faxnumField, value) != true)) {
                    this.faxnumField = value;
                    this.RaisePropertyChanged("faxnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phonenum {
            get {
                return this.phonenumField;
            }
            set {
                if ((object.ReferenceEquals(this.phonenumField, value) != true)) {
                    this.phonenumField = value;
                    this.RaisePropertyChanged("phonenum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string specialinstructions {
            get {
                return this.specialinstructionsField;
            }
            set {
                if ((object.ReferenceEquals(this.specialinstructionsField, value) != true)) {
                    this.specialinstructionsField = value;
                    this.RaisePropertyChanged("specialinstructions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string staddress1 {
            get {
                return this.staddress1Field;
            }
            set {
                if ((object.ReferenceEquals(this.staddress1Field, value) != true)) {
                    this.staddress1Field = value;
                    this.RaisePropertyChanged("staddress1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string staddress2 {
            get {
                return this.staddress2Field;
            }
            set {
                if ((object.ReferenceEquals(this.staddress2Field, value) != true)) {
                    this.staddress2Field = value;
                    this.RaisePropertyChanged("staddress2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string staddress3 {
            get {
                return this.staddress3Field;
            }
            set {
                if ((object.ReferenceEquals(this.staddress3Field, value) != true)) {
                    this.staddress3Field = value;
                    this.RaisePropertyChanged("staddress3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state {
            get {
                return this.stateField;
            }
            set {
                if ((object.ReferenceEquals(this.stateField, value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stcity {
            get {
                return this.stcityField;
            }
            set {
                if ((object.ReferenceEquals(this.stcityField, value) != true)) {
                    this.stcityField = value;
                    this.RaisePropertyChanged("stcity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stcountry {
            get {
                return this.stcountryField;
            }
            set {
                if ((object.ReferenceEquals(this.stcountryField, value) != true)) {
                    this.stcountryField = value;
                    this.RaisePropertyChanged("stcountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ststate {
            get {
                return this.ststateField;
            }
            set {
                if ((object.ReferenceEquals(this.ststateField, value) != true)) {
                    this.ststateField = value;
                    this.RaisePropertyChanged("ststate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stzip {
            get {
                return this.stzipField;
            }
            set {
                if ((object.ReferenceEquals(this.stzipField, value) != true)) {
                    this.stzipField = value;
                    this.RaisePropertyChanged("stzip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string zip {
            get {
                return this.zipField;
            }
            set {
                if ((object.ReferenceEquals(this.zipField, value) != true)) {
                    this.zipField = value;
                    this.RaisePropertyChanged("zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="customergetspecialinstructionresult", Namespace="http://services.it.tcg/epicor/customerservice")]
    [System.SerializableAttribute()]
    public partial class customergetspecialinstructionresult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string exceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] epicorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string exception {
            get {
                return this.exceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.exceptionField, value) != true)) {
                    this.exceptionField = value;
                    this.RaisePropertyChanged("exception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string[] epicor {
            get {
                return this.epicorField;
            }
            set {
                if ((object.ReferenceEquals(this.epicorField, value) != true)) {
                    this.epicorField = value;
                    this.RaisePropertyChanged("epicor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.it.tcg/epicor/customerservice", ConfigurationName="CustomerServiceReference.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.it.tcg/epicor/customerservice/ICustomerService/getallcustomers", ReplyAction="http://services.it.tcg/epicor/customerservice/ICustomerService/getallcustomersRes" +
            "ponse")]
        WindowsConsoleClient.CustomerServiceReference.customergetallresult getallcustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.it.tcg/epicor/customerservice/ICustomerService/getcustomerbycusti" +
            "d", ReplyAction="http://services.it.tcg/epicor/customerservice/ICustomerService/getcustomerbycusti" +
            "dResponse")]
        WindowsConsoleClient.CustomerServiceReference.customergetsingleresult getcustomerbycustid(string custid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.it.tcg/epicor/customerservice/ICustomerService/getspecialinstruct" +
            "ion", ReplyAction="http://services.it.tcg/epicor/customerservice/ICustomerService/getspecialinstruct" +
            "ionResponse")]
        WindowsConsoleClient.CustomerServiceReference.customergetspecialinstructionresult getspecialinstruction(string custid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : WindowsConsoleClient.CustomerServiceReference.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<WindowsConsoleClient.CustomerServiceReference.ICustomerService>, WindowsConsoleClient.CustomerServiceReference.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WindowsConsoleClient.CustomerServiceReference.customergetallresult getallcustomers() {
            return base.Channel.getallcustomers();
        }
        
        public WindowsConsoleClient.CustomerServiceReference.customergetsingleresult getcustomerbycustid(string custid) {
            return base.Channel.getcustomerbycustid(custid);
        }
        
        public WindowsConsoleClient.CustomerServiceReference.customergetspecialinstructionresult getspecialinstruction(string custid) {
            return base.Channel.getspecialinstruction(custid);
        }
    }
}
